spring:
  application:
    name: spring-security
  # ======= H2 Console =======
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
app:
  auth:
    mode: memory #db
server:
  port: 8083
logging:
  level:
    org:
      springframework:
        security: debug
